{
 "title": "Server Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "% CPU per Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 * avg(rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])) by (cpu) /\r\n    avg(rate(node_cpu_seconds_total[1m])) by (cpu)",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "% Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 * (1 - (avg(node_memory_MemAvailable_bytes[1m]) / avg(node_memory_MemTotal_bytes[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Espaço livre",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/\"}/node_filesystem_size_bytes{mountpoint=\"/\"}*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rede",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}